### ISSUE TITLE
Promote PuppetPadchat to SOLO NPM Module wechaty-puppet-padchat

### ISSUE THREAD

**Issue by zixia** [Chatie/wechaty#1372]
Decouple all puppet implementations as single NPM module.

See: https://github.com/lijiarui/wechaty-puppet-padchat/issues/67

### TODO

- [x] Move source codes to its own GitHub Repository
  - [x] Add description & links to repository title
  - [ ] Enable GitHub Pages for this repository on branch `/docs`
  - [ ] Publish Padchat Logo in `/docs/images/wechaty-padchat-logo.png`
- [x] Create NPM module `wechaty-puppet-padchat`
  - [x] Add NPM Badge to README
  - [ ] Test @`latest` and @`next` for different minor versions(odd for @`next`, even for @`latest`)
- [x] Enable Travis CI
  - [ ] Pass Testing
  - [x] Enable Travis CI Packing & Deployment
  - [x] Add Travis CI Badge to README
- [ ] Fix Basic Errors in Wechaty Document at <https://chatie.io/wechaty/>
  - [ ] Sync all the BREAKING CHANGES
  - [ ] Some class methods are leaking of documentation
  - [ ] Hide methods from the docs which is not Public API.
- [ ] Refine the Getting Started with Wechaty Tutorials
  - [ ] Make sure the repository(<https://github.com/lijiarui/wechaty-getting-started>) is working perfectly with the latest code
  - [ ] Move the repo under Chatie Org
  - [ ] Re-record the Tutorial Video
  - [ ] Re-publish the Tutorial Video on Youtube/Tencent
  - [ ] Update the video in blog post at <https://blog.chatie.io/getting-started-wechaty/>
  - [ ] Fix the code part of the blog post <https://blog.chatie.io/getting-started-wechaty/>
- [ ] Publish Wechaty v0.18 Migration Guide on Blog

Related to #1442

**Comment by zixia** [comment]
Almost done.

**Comment by zixia** [comment]
Related to #1442

**Comment by zixia** [comment]
Perfect done.
